name: Prod Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1.0.1
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          dokku-host: "13.127.245.149"
          ssh-port: "22"
          app-name: "crm-backend"
          git-push-flags: "--force"

      - name: Cleanup old images
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: "13.235.77.169"
          username: ubuntu
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          port: "22"
          script: |
            sudo dokku cleanup
